name: hylfm_wo_care
channels:
  - pytorch
  - conda-forge
  - defaults
  - fynnbe
dependencies:
  - cudatoolkit
  - dill
  - h5py>=2.9.0
  - ignite 0.3.*
  - imagecodecs
  - jupyter
  - matplotlib>=3.3.2
  - numpy>=1.16.3
  - pip>=19.1
  - plotly
  - pytest
  - python>=3.7.3
  - pytorch-msssim
  - pytorch>=1.4.0
  - pyyaml>=5.1
  - ruamel.yaml
  - scikit-image>=0.15.0
  - scikit-learn>=0.20.3
  - scipy>=1.2.1
  - seaborn
  - six
  - tensorboard 1.15
  - tifffile>=0.15.1
  - torchvision>=0.2.1
  - tqdm
  - typing_extensions
  - z5py>=1.4.1
