- name: SmoothL1Loss
  scale_minimize_vs: &scale_minimize_vs [pred, mse, lr]
  tensor_names: &tensor_names {prediction: pred, target: lr}
  loss_kwargs: {}
- name: SmoothL1Loss
  scale_minimize_vs: *scale_minimize_vs
  along_dim__dim_len: &along_dim__dim_len [1, 49]
  tensor_names: *tensor_names
  loss_kwargs: {}
- name: MS_SSIM
  scale_minimize_vs: *scale_minimize_vs
  tensor_names: *tensor_names
  loss_kwargs:
    channel: 1
    data_range: &data_range 1
    size_average: true
    spatial_dims: 3
    win_sigma: 1.5
    win_size: 11
- name: MS_SSIM
  along_dim__dim_len: *along_dim__dim_len
  scale_minimize_vs: *scale_minimize_vs
  tensor_names: *tensor_names
  loss_kwargs:
    data_range: *data_range
    size_average: true
    win_size: 11
    win_sigma: 1.5
    channel: 1
    spatial_dims: 2
- name: SSIM
  scale_minimize_vs: *scale_minimize_vs
  tensor_names: *tensor_names
  loss_kwargs:
    data_range: *data_range
    size_average: true
    win_size: 11
    win_sigma: 1.5
    channel: 1
    spatial_dims: 3
- name: NRMSE
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
- name: NRMSE
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  along_dim__dim_len: *along_dim__dim_len
- name: PSNR
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  data_range: *data_range
- name: PSNR
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  along_dim__dim_len: *along_dim__dim_len
  data_range: *data_range
- name: MSELoss
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  loss_kwargs: {}
- name: MSELoss
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  along_dim__dim_len: *along_dim__dim_len
  loss_kwargs: {}
- name: BeadPrecisionRecall
  tensor_names: {prediction: pred, target: lr, meta: meta}
  scale_minimize_vs: *scale_minimize_vs
  dist_threshold: 3.0
  exclude_border: false
  max_sigma: 6.0
  min_sigma: 1.0
  overlap: 0.5
  sigma_ratio: 3.0
  threshold: .05
  tgt_threshold: .05
  scaling: [2., 0.7, 0.7]
