- name: SmoothL1Loss
  scale_minimize_vs: &scale_minimize_vs [lr_slice, mse, ls_slice]
  tensor_names: &tensor_names {prediction: lr_slice, target: ls_slice}
  loss_kwargs: {}
- name: MS_SSIM
  scale_minimize_vs: *scale_minimize_vs
  tensor_names: *tensor_names
  loss_kwargs:
    channel: 1
    data_range: &data_range 1
    size_average: true
    spatial_dims: 2
    win_sigma: 1.5
    win_size: 11
- name: SSIM
  scale_minimize_vs: *scale_minimize_vs
  tensor_names: *tensor_names
  loss_kwargs:
    data_range: *data_range
    size_average: true
    win_size: 11
    win_sigma: 1.5
    channel: 1
    spatial_dims: 2
- name: NRMSE
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
- name: PSNR
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  data_range: *data_range
- name: MSELoss
  tensor_names: *tensor_names
  scale_minimize_vs: *scale_minimize_vs
  loss_kwargs: {}
