toolbox: # defines yaml anchors
  precision: &precision float
  nnum: &nnum 19
  z_out: &z_out 51
  shrink: &shrink 8
  nshrink: &nshrink -8
  ls_roi: &ls_roi [[0, null], [35, -35], [*shrink, *nshrink], [*shrink, *nshrink]]
  eval_log: &eval_log
    TqdmLogger: {}
    TensorBoardLogger:
      scalars_every: {value: 1, unit: epoch}
      tensors_every: {value: 1, unit: epoch}
      tensor_names: [lf, pred, ls_reg]
    FileLogger:
      scalars_every: {value: 1, unit: iteration}
      tensors_every: {value: 1, unit: iteration}
      tensor_names: [pred, ls_reg]

  eval_batch_size: &eval_batch_size 1
  sample_trfs: &sample_trfs
    - Resize: {apply_to: ls_reg, shape: [1.0, 121, 0.42105263157894736842105263157895, 0.42105263157894736842105263157895, ], order: 2}  # 0.42105263157894736842105263157895‬=8/19
    - Assert: {apply_to: ls_reg, expected_tensor_shape: [1, 121, null, null]}
  eval_sample_prepr: &eval_sample_prepr
    - Crop: {apply_to: ls_reg, crop: *ls_roi}
    - Normalize01: {apply_to: lf, min_percentile: 5.0, max_percentile: 99.8}
    - Normalize01: {apply_to: ls_reg, min_percentile: 5.0, max_percentile: 99.99}
    - ChannelFromLightField: {apply_to: {lf: lfc}, nnum: *nnum}
  eval_batch_prepr: &eval_batch_prepr []
  batch_prepr_in_step: &batch_prepr_in_step
    - Cast: {apply_to: [lfc, ls_reg], dtype: *precision, device: cuda, non_blocking: true}
  batch_postpr: &batch_postpr []

model:
  name: A04
  kwargs:
    scale: 8
    shrink: *shrink
    input_name: lfc
    prediction_name: pred
    nnum: *nnum
    z_out: *z_out
  precision: *precision

stages:
  - train:
      max_epochs: 500
      metrics: []
      log:
        TqdmLogger: {}
        TensorBoardLogger:
          scalars_every: {value: 1, unit: iteration}
          tensors_every: {value: 1, unit: epoch}
          tensor_names: [lf, pred, ls_reg]

      criterion:
        name: WeightedSmoothL1Loss
        kwargs: {threshold: 0.5, initial_weight: .05, apply_below_threshold: true, decay_by: .8, every_nth_epoch: 1}
        tensor_names: {prediction: pred, target: ls_reg}

      optimizer:
        name: Adam
        kwargs: {lr: 2.0e-4, eps: 1.0e-8}

      sampler:
        base: RandomSampler
        drop_last: false

      batch_preprocessing:
        - RandomRotate90: {apply_to: [lf, ls_reg]}
        - ChannelFromLightField: {apply_to: {lf: lfc}, nnum: *nnum}
      batch_preprocessing_in_step: *batch_prepr_in_step
      batch_postprocessing: *batch_postpr

      data:
        - batch_size: 1
          sample_preprocessing:
            - Crop: {apply_to: ls_reg, crop: *ls_roi}
            - Normalize01: {apply_to: lf, min_percentile: 5.0, max_percentile: 99.8}
            - Normalize01: {apply_to: ls_reg, min_percentile: 5.0, max_percentile: 99.99}
            - AdditiveGaussianNoise: {apply_to: lf, sigma: 0.1}
            - AdditiveGaussianNoise: {apply_to: ls_reg, sigma: 0.05}
            - RandomIntensityScale: {apply_to: [lf, ls_reg], factor_min: .8, factor_max: 1.2}
            - RandomlyFlipAxis: {apply_to: [lf, ls_reg], axis: -1}
            - RandomlyFlipAxis: {apply_to: [lf, ls_reg], axis: -2}

          datasets:
            - {tensors: {lf: beads.small_2, ls_reg: beads.small_2}, indices: null}

      validate:
        metrics: beads.yml
        log: *eval_log
        score_metric: smooth_l1_loss-scaled
        period: {value: 1, unit: epoch}
        patience: 10
        batch_preprocessing: *eval_batch_prepr
        batch_preprocessing_in_step: *batch_prepr_in_step
        batch_postprocessing: *batch_postpr
        data:
          - batch_size: *eval_batch_size
            sample_preprocessing: *eval_sample_prepr
            datasets:
              - {tensors: {lf: beads.small_0, ls_reg: beads.small_0}, sample_transformations: *sample_trfs, indices: null}

  - test:
      metrics: beads.yml
      log: *eval_log
      batch_preprocessing: *eval_batch_prepr
      batch_preprocessing_in_step: *batch_prepr_in_step
      batch_postprocessing: *batch_postpr
      data:
        - batch_size: *eval_batch_size
          sample_preprocessing: *eval_sample_prepr
          datasets:
            - {tensors: {lf: beads.small_1, ls_reg: beads.small_1}, sample_transformations: *sample_trfs}
